---
image: python:2.7
variables:
  PYTHONDONTWRITEBYTECODE: "1"
  PIP_CACHE_DIR: ".cache/pip"
cache:
  paths:
    - ".cache"
before_script:
  - if [[ "$(basename $(pwd))" != "migrant" ]]; then exit 10; fi  # stop us early if dirname is wrong
  - pip install -r requirements.txt
  - apt-get update
test:
  script:
  - make test