language: python
sudo: false
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
install:
  - pip install tox-travis coveralls
script:
  - tox
notifications:
    email: false
after_success:
  - coveralls
